// mobile/components/product-card.tsx
import { Text } from '@/components/ui/text';
import { formatIdr, mediaUrl } from '@/lib/format';
import type { Product } from '@/lib/api';
import { Image } from 'expo-image';
import { Link } from 'expo-router';
import { Pressable, View } from 'react-native';

export function ProductCard({ product }: { product: Product }) {
  const hasSale = product.compare_price != null && product.compare_price > (product.price ?? 0);
  return (
    <Link href={`/product/${product.slug}`} asChild>
      <Pressable className="mb-3 w-[48%] overflow-hidden rounded-md border border-border bg-card">
        <View className="relative">
          <Image
            source={{ uri: mediaUrl(product.thumbnail ?? product.images?.[0]?.url) }}
            style={{ width: '100%', height: 148, backgroundColor: '#f4f4f5' }}
            contentFit="cover"
          />
          {hasSale ? (
            <View className="absolute left-2 top-2 rounded-full bg-om-sale px-2 py-0.5">
              <Text className="text-[10px] font-bold text-white">SALE</Text>
            </View>
          ) : null}
        </View>
        <View className="gap-1 p-3">
          <Text className="text-[11px] font-medium text-muted-foreground" numberOfLines={1}>
            {product.brand?.name ?? 'OceanMall'}
          </Text>
          <Text className="text-[13px] font-semibold leading-tight" numberOfLines={2}>
            {product.name}
          </Text>
          <View className="flex-row items-baseline gap-1.5">
            <Text className="text-[13px] font-bold text-om-navy">{formatIdr(product.price)}</Text>
            {hasSale ? (
              <Text className="text-[11px] text-muted-foreground line-through">
                {formatIdr(product.compare_price)}
              </Text>
            ) : null}
          </View>
        </View>
      </Pressable>
    </Link>
  );
}

// resources/js/components/shop/product-card.vue
<script setup lang="ts">
import { Link } from '@inertiajs/vue3';
import { computed } from 'vue';
import PriceDisplay from '@/components/shop/price-display.vue';
import { Badge } from '@/components/ui/badge';
import * as shop from '@/routes/shop';
import type { Product } from '@/types/shop';

const props = defineProps<{ product: Product }>();

const thumbnail = computed<string | null>(
    () => props.product.thumbnail ?? props.product.images?.[0]?.url ?? null,
);

const price = computed(() => props.product.prices?.[0] ?? null);

const percentage = computed<number | null>(() => {
    if (
        price.value?.amount == null ||
        !price.value?.compare_amount ||
        price.value.compare_amount <= price.value.amount
    ) {
        return null;
    }
    return Math.round(
        ((price.value.compare_amount - price.value.amount) /
            price.value.compare_amount) *
            100,
    );
});
</script>

<template>
    <div class="relative">
        <div class="relative aspect-square overflow-hidden rounded-md bg-muted">
            <img
                v-if="thumbnail"
                :src="thumbnail"
                :alt="product.name"
                loading="lazy"
                class="size-full object-cover object-center"
            />
            <Badge
                v-if="percentage"
                variant="sale"
                class="absolute top-1.5 left-1.5 px-1.5 py-0.5 text-[10px] font-bold"
            >
                -{{ percentage }}%
            </Badge>
        </div>

        <h3
            class="mt-2 line-clamp-2 text-[12px] leading-snug font-medium text-foreground"
        >
            <Link :href="shop.product.url({ product: product.slug })">
                <span class="absolute inset-0" />
                {{ product.name }}
            </Link>
        </h3>

        <p v-if="product.brand" class="mt-0.5 text-[10px] text-muted-foreground">
            {{ product.brand.name }}
        </p>

        <div class="mt-1">
            <PriceDisplay :price="price ?? null" size="sm" />
        </div>
    </div>
</template>
